Feature losses
hbbOooO/hnu-nlp pull request #11
Opened 2024-01-27 07:39 UTC by WangZijian7

为losses.py添加注释。

2024-01-27 12:48 UTC, hbbOooO requested changes

2024-01-27 12:48 UTC, hbbOooO commented on common/losses.py
> +class LabelSmootherLoss(BaseLoss):
谢谢子健，这个LabelSmootherLoss之后的代码都删掉吧。再push一次。

2024-01-29 13:40 UTC, WangZijian7 commented on common/losses.py
> +class LabelSmootherLoss(BaseLoss):
杰哥，我删除后重新push了，需要重新提交PR请求吗？另外，我push上来的有一个.ipynb.checkpoint，我明明在命令行里remove它了，但是push的时候还是一起传上来了。

2024-01-29 13:41 UTC, WangZijian7 commented on common/losses.py
> +class LabelSmootherLoss(BaseLoss):
> 谢谢子健，这个LabelSmootherLoss之后的代码都删掉吧。再push一次。

杰哥，我删除后重新push了，需要重新提交PR请求吗？另外，我push上来的有一个.ipynb.checkpoint，我明明在命令行里remove它了，但是push的时候还是一起传上来了。

2024-01-29 14:34 UTC, hbbOooO commented on common/losses.py
> +class LabelSmootherLoss(BaseLoss):
> > 谢谢子健，这个LabelSmootherLoss之后的代码都删掉吧。再push一次。
> 
> 杰哥，我删除后重新push了，需要重新提交PR请求吗？另外，我push上来的有一个.ipynb.checkpoint，我明明在命令行里remove它了，但是push的时候还是一起传上来了。

1）不需要的，你在这个PR的commit页面能看到一个名叫wzj的提交，你点进去能看到你最新的push内容。
2）这个.ipynb.checkpoint有办法删除吗？如果能删除，可以再push一次，如果没有办法就算了。

2024-01-31 12:13 UTC, WangZijian7 commented on common/losses.py
> +class LabelSmootherLoss(BaseLoss):
> 1）不需要的，你在这个PR的commit页面能看到一个名叫wzj的提交，你点进去能看到你最新的push内容。 2）这个.ipynb.checkpoint有办法删除吗？如果能删除，可以再push一次，如果没有办法就算了。

1）好的，已经看到了。
2）已经删除了。

2024-02-01 01:31 UTC, hbbOooO approved these changes

2024-02-01 01:31 UTC, merged