Feature logger by wzj
hbbOooO/hnu-nlp pull request #18
Opened 2024-02-05 10:20 UTC by WangZijian7

为日志logger写了注释。

2024-02-05 15:12 UTC, hbbOooO requested changes

2024-02-05 15:12 UTC, hbbOooO commented on common/logger.py
> +    def set_config(cls, filename=None, level='info', format='%(asctime)s - %(levelname)s: %(message)s')-> None:
子健，这里麻烦加上类型
def set_config(cls, filename:str = None, level:str = 'info', format:str = '%(asctime)s - %(levelname)s: %(message)s')-> None:

2024-02-07 15:20 UTC, WangZijian7 commented on common/logger.py
> +    def set_config(cls, filename=None, level='info', format='%(asctime)s - %(levelname)s: %(message)s')-> None:
> 子健，这里麻烦加上类型 def set_config(cls, filename:str = None, level:str = 'info', format:str = '%(asctime)s - %(levelname)s: %(message)s')-> None:

已经添加上了，杰哥。

2024-02-08 03:32 UTC, hbbOooO approved these changes

2024-02-08 03:32 UTC, merged